package com.permitping.infrastructure;

import com.permitping.domain.Role;
import java.nio.file.*;
import java.sql.*;

public final class Database {
    private final String url;
    public Database(Path path) {
        try { Files.createDirectories(path.toAbsolutePath().getParent()); } catch (Exception e) { throw new IllegalStateException("Cannot create data directory", e); }
        url="jdbc:sqlite:"+path.toAbsolutePath();
        try(Connection c=connect();Statement s=c.createStatement()){s.executeUpdate("CREATE TABLE IF NOT EXISTS documents (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, type TEXT NOT NULL, holder TEXT NOT NULL, project TEXT, expires_on TEXT NOT NULL, file_path TEXT, notes TEXT, archived_at TEXT)");s.executeUpdate("CREATE TABLE IF NOT EXISTS document_versions (id INTEGER PRIMARY KEY AUTOINCREMENT, document_id INTEGER NOT NULL, version INTEGER NOT NULL, file_path TEXT NOT NULL, created_at TEXT NOT NULL, FOREIGN KEY(document_id) REFERENCES documents(id) ON DELETE CASCADE)");s.executeUpdate("CREATE TABLE IF NOT EXISTS profiles (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL COLLATE NOCASE UNIQUE, profile_type TEXT NOT NULL, email TEXT, phone TEXT, notes TEXT)");s.executeUpdate("CREATE TABLE IF NOT EXISTS project_assignments (id INTEGER PRIMARY KEY AUTOINCREMENT, project_name TEXT NOT NULL, profile_id INTEGER NOT NULL, status TEXT NOT NULL, notes TEXT, UNIQUE(project_name, profile_id), FOREIGN KEY(profile_id) REFERENCES profiles(id))");s.executeUpdate("CREATE TABLE IF NOT EXISTS reminder_settings (days_before INTEGER PRIMARY KEY, enabled INTEGER NOT NULL)");s.executeUpdate("CREATE TABLE IF NOT EXISTS reminder_history (document_id INTEGER NOT NULL, days_before INTEGER NOT NULL, sent_at TEXT NOT NULL, PRIMARY KEY(document_id, days_before))");s.executeUpdate("CREATE TABLE IF NOT EXISTS requirement_templates (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL UNIQUE)");s.executeUpdate("CREATE TABLE IF NOT EXISTS template_requirements (template_id INTEGER NOT NULL, document_type TEXT NOT NULL, PRIMARY KEY(template_id, document_type), FOREIGN KEY(template_id) REFERENCES requirement_templates(id) ON DELETE CASCADE)");s.executeUpdate("CREATE TABLE IF NOT EXISTS project_requirement_templates (project_name TEXT PRIMARY KEY, template_id INTEGER NOT NULL, FOREIGN KEY(template_id) REFERENCES requirement_templates(id))");migrate(c);seedReminderSettings(c);seedTemplates(c);}
        catch(SQLException e){throw new IllegalStateException("Cannot initialize database",e);}
    }
    public Connection connect() throws SQLException { Connection c=DriverManager.getConnection(url);try(Statement s=c.createStatement()){s.execute("PRAGMA busy_timeout=5000");s.execute("PRAGMA foreign_keys=ON");}return c; }
    private void migrate(Connection c) throws SQLException { try(Statement s=c.createStatement();ResultSet r=s.executeQuery("PRAGMA user_version")){int version=r.next()?r.getInt(1):0;if(version<1){addColumnIfMissing(s,"documents","archived_at TEXT");s.execute("PRAGMA user_version=1");}if(version<2){addColumnIfMissing(s,"profiles","archived_at TEXT");addColumnIfMissing(s,"documents","holder_profile_id INTEGER");s.execute("PRAGMA user_version=2");}if(version<3){addColumnIfMissing(s,"profiles","notification_enabled INTEGER NOT NULL DEFAULT 0");addColumnIfMissing(s,"profiles","notification_channel TEXT NOT NULL DEFAULT 'NONE'");s.execute("UPDATE profiles SET notification_channel='NONE' WHERE notification_channel IS NULL OR notification_channel='' ");s.execute("PRAGMA user_version=3");}if(version<4){s.executeUpdate("CREATE TABLE IF NOT EXISTS reminder_deliveries (id INTEGER PRIMARY KEY AUTOINCREMENT, document_id INTEGER NOT NULL, profile_id INTEGER NOT NULL, days_before INTEGER NOT NULL, channel TEXT NOT NULL, recipient TEXT NOT NULL, status TEXT NOT NULL, attempted_at TEXT NOT NULL, provider_message_id TEXT, error_message TEXT, attempts INTEGER NOT NULL DEFAULT 0)");s.execute("PRAGMA user_version=4");}if(version<5){s.executeUpdate("CREATE TABLE IF NOT EXISTS auth_users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT NOT NULL UNIQUE COLLATE NOCASE, display_name TEXT NOT NULL, password_hash TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)");s.executeUpdate("CREATE TABLE IF NOT EXISTS auth_user_roles (user_id INTEGER PRIMARY KEY, role_name TEXT NOT NULL, FOREIGN KEY(user_id) REFERENCES auth_users(id) ON DELETE CASCADE)");s.execute("PRAGMA user_version=5");}if(version<6){s.executeUpdate("CREATE TABLE IF NOT EXISTS auth_roles (name TEXT PRIMARY KEY COLLATE NOCASE, permissions TEXT NOT NULL, system INTEGER NOT NULL DEFAULT 0)");for(Role role:new Role[]{Role.ADMIN,Role.MANAGER,Role.EDITOR,Role.VIEWER}){try(PreparedStatement p=c.prepareStatement("INSERT OR IGNORE INTO auth_roles(name,permissions,system) VALUES(?,?,1)")){p.setString(1,role.name());p.setString(2,String.join(",",role.permissions().stream().map(Enum::name).toList()));p.executeUpdate();}}s.execute("PRAGMA user_version=6");}} }
    private void addColumnIfMissing(Statement s,String table,String definition)throws SQLException{try{s.executeUpdate("ALTER TABLE "+table+" ADD COLUMN "+definition);}catch(SQLException e){if(!e.getMessage().toLowerCase().contains("duplicate column name"))throw e;}}
    private void seedReminderSettings(Connection c) throws SQLException { try(PreparedStatement p=c.prepareStatement("INSERT OR IGNORE INTO reminder_settings(days_before,enabled) VALUES(?,1)")){for(int days:new int[]{90,60,30,14,7}){p.setInt(1,days);p.addBatch();}p.executeBatch();} }
    private void seedTemplates(Connection c) throws SQLException { String[][] seeds={{"General contractor","License","Insurance certificate","Permit"},{"Electrical subcontractor","License","Insurance certificate","OSHA card"},{"Commercial renovation","License","Insurance certificate","Permit"},{"OSHA-sensitive project","License","Insurance certificate","OSHA card","Permit"}};for(String[] seed:seeds){long id;try(PreparedStatement p=c.prepareStatement("INSERT OR IGNORE INTO requirement_templates(name) VALUES(?)",Statement.RETURN_GENERATED_KEYS)){p.setString(1,seed[0]);p.executeUpdate();}try(PreparedStatement p=c.prepareStatement("SELECT id FROM requirement_templates WHERE name=?")){p.setString(1,seed[0]);try(ResultSet r=p.executeQuery()){r.next();id=r.getLong(1);}}try(PreparedStatement p=c.prepareStatement("INSERT OR IGNORE INTO template_requirements(template_id,document_type) VALUES(?,?)")){for(int i=1;i<seed.length;i++){p.setLong(1,id);p.setString(2,seed[i]);p.addBatch();}p.executeBatch();}} }
}
