package com.permitping.infrastructure;

import com.permitping.application.AuthRepository;
import com.permitping.domain.*;
import java.sql.*;
import java.util.*;

public final class SqliteAuthRepository implements AuthRepository {
    private final Database database;
    public SqliteAuthRepository(Database database) { this.database = database; }
    public long countUsers() { try (Connection c=database.connect(); Statement s=c.createStatement(); ResultSet r=s.executeQuery("SELECT COUNT(*) FROM auth_users")) { return r.next()?r.getLong(1):0; } catch(SQLException e){throw failure("count users",e);} }
    public void saveUser(String username,String displayName,String passwordHash,Role role) { try(Connection c=database.connect()){ c.setAutoCommit(false); try(PreparedStatement p=c.prepareStatement("INSERT INTO auth_users(username,display_name,password_hash,active) VALUES(?,?,?,1)",Statement.RETURN_GENERATED_KEYS)){p.setString(1,username);p.setString(2,displayName);p.setString(3,passwordHash);p.executeUpdate();try(ResultSet keys=p.getGeneratedKeys()){keys.next();long id=keys.getLong(1);try(PreparedStatement r=c.prepareStatement("INSERT INTO auth_user_roles(user_id,role_name) VALUES(?,?)")){r.setLong(1,id);r.setString(2,role.name());r.executeUpdate();}}} c.commit(); } catch(SQLException e){throw failure("save user",e);} }
    public StoredUser findByUsername(String username) { String sql="SELECT u.id,u.username,u.display_name,u.active,u.password_hash,r.role_name FROM auth_users u JOIN auth_user_roles r ON r.user_id=u.id WHERE u.username=?"; try(Connection c=database.connect();PreparedStatement p=c.prepareStatement(sql)){p.setString(1,username);try(ResultSet r=p.executeQuery()){if(!r.next())return null;AuthUser user=new AuthUser(r.getLong(1),r.getString(2),r.getString(3),findRole(c,r.getString(6)),r.getBoolean(4));return new StoredUser(user,r.getString(5));}}catch(SQLException|IllegalArgumentException e){throw failure("find user",e);} }
    public List<AuthUser> findUsers(){List<AuthUser> out=new ArrayList<>();String sql="SELECT u.id,u.username,u.display_name,u.active,r.role_name FROM auth_users u JOIN auth_user_roles r ON r.user_id=u.id ORDER BY u.username";try(Connection c=database.connect();PreparedStatement s=c.prepareStatement(sql);ResultSet r=s.executeQuery()){while(r.next())out.add(new AuthUser(r.getLong(1),r.getString(2),r.getString(3),findRole(c,r.getString(5)),r.getBoolean(4)));return out;}catch(SQLException|IllegalArgumentException e){throw failure("load users",e);}}
    public void setActive(long id,boolean active){try(Connection c=database.connect();PreparedStatement p=c.prepareStatement("UPDATE auth_users SET active=? WHERE id=?")){p.setBoolean(1,active);p.setLong(2,id);if(p.executeUpdate()!=1)throw new IllegalArgumentException("User not found");}catch(SQLException e){throw failure("update user",e);}}
    public void setRole(long id,Role role){if(role==null)throw new IllegalArgumentException("Role is required");try(Connection c=database.connect();PreparedStatement p=c.prepareStatement("UPDATE auth_user_roles SET role_name=? WHERE user_id=?")){p.setString(1,role.name());p.setLong(2,id);if(p.executeUpdate()!=1)throw new IllegalArgumentException("User not found");}catch(SQLException e){throw failure("update role",e);}}
    public void updatePassword(long id,String passwordHash){if(passwordHash==null||passwordHash.isBlank())throw new IllegalArgumentException("Password hash is required");try(Connection c=database.connect();PreparedStatement p=c.prepareStatement("UPDATE auth_users SET password_hash=? WHERE id=?")){p.setString(1,passwordHash);p.setLong(2,id);if(p.executeUpdate()!=1)throw new IllegalArgumentException("User not found");}catch(SQLException e){throw failure("update password",e);}}
    public List<Role> findRoles(){List<Role> out=new ArrayList<>();try(Connection c=database.connect();Statement s=c.createStatement();ResultSet r=s.executeQuery("SELECT name,permissions,system FROM auth_roles ORDER BY system DESC,name")){while(r.next())out.add(readRole(r.getString(1),r.getString(2),r.getBoolean(3)));return out;}catch(SQLException|IllegalArgumentException e){throw failure("load roles",e);}}
    public Role findRole(String name){try(Connection c=database.connect()){return findRole(c,name);}catch(SQLException|IllegalArgumentException e){throw failure("find role",e);}}
    private Role findRole(Connection c,String name)throws SQLException{try(PreparedStatement p=c.prepareStatement("SELECT name,permissions,system FROM auth_roles WHERE name=?")){p.setString(1,name);try(ResultSet r=p.executeQuery()){if(!r.next())throw new IllegalArgumentException("Role not found: "+name);return readRole(r.getString(1),r.getString(2),r.getBoolean(3));}}}
    private Role readRole(String name,String permissions,boolean system){EnumSet<Permission> values=EnumSet.noneOf(Permission.class);if(permissions!=null&&!permissions.isBlank())for(String value:permissions.split(","))values.add(Permission.valueOf(value));return system?Role.builtIn(name):Role.custom(name,values);}
    public void saveRole(Role role){if(role==null||role.system())throw new IllegalArgumentException("Only custom roles can be created");try(Connection c=database.connect();PreparedStatement p=c.prepareStatement("INSERT INTO auth_roles(name,permissions,system) VALUES(?,?,0)")){p.setString(1,role.name());p.setString(2,encode(role));p.executeUpdate();}catch(SQLException e){throw failure("save role",e);}}
    public void updateRole(Role role){if(role==null||role.system())throw new IllegalArgumentException("Only custom roles can be changed");try(Connection c=database.connect();PreparedStatement p=c.prepareStatement("UPDATE auth_roles SET permissions=? WHERE name=? AND system=0")){p.setString(1,encode(role));p.setString(2,role.name());if(p.executeUpdate()!=1)throw new IllegalArgumentException("Custom role not found");}catch(SQLException e){throw failure("update role",e);}}
    public void deleteRole(String name){try(Connection c=database.connect();PreparedStatement p=c.prepareStatement("DELETE FROM auth_roles WHERE name=? AND system=0")){p.setString(1,name);if(p.executeUpdate()!=1)throw new IllegalArgumentException("Custom role not found");}catch(SQLException e){throw failure("delete role",e);}}
    public long countUsersWithRole(String name){try(Connection c=database.connect();PreparedStatement p=c.prepareStatement("SELECT COUNT(*) FROM auth_user_roles WHERE role_name=?")){p.setString(1,name);try(ResultSet r=p.executeQuery()){return r.next()?r.getLong(1):0;}}catch(SQLException e){throw failure("count role users",e);}}
    private String encode(Role role){return String.join(",",role.permissions().stream().map(Enum::name).sorted().toList());}
    private IllegalStateException failure(String action,Exception e){return new IllegalStateException("Could not "+action,e);}
}
