package com.permitping.ui;

import com.permitping.application.*;
import com.permitping.domain.*;
import javafx.collections.FXCollections;
import javafx.geometry.Insets;
import javafx.geometry.Orientation;
import javafx.scene.control.*;
import javafx.scene.layout.*;
import java.util.*;

public final class AssignmentsPage extends BorderPane {
    private final AssignmentService assignments; private final ProfileService profiles; private final ClearanceService clearance; private final List<String> projects; private final NotificationService notifications;
    private final ListView<AssignmentClearance> list = new ListView<>();
    private final Label selectedDetails = new Label("Select an assignment to see its readiness details.");
    public AssignmentsPage(AssignmentService assignments, ProfileService profiles, ClearanceService clearance, List<String> projects, NotificationService notifications) {
        this.assignments=assignments; this.profiles=profiles; this.clearance=clearance; this.projects=projects; this.notifications=notifications;
        getStyleClass().add("page-shell"); setPadding(new Insets(30,34,30,34)); setTop(new PageHeader("Assignments", "See who is assigned to each project and whether their compliance evidence is clear.")); VBox.setVgrow(list, Priority.ALWAYS); list.setMinHeight(220);
        list.setPlaceholder(new Label("No assignments yet. Add a profile to a project to start tracking readiness."));
        list.setCellFactory(view -> new ListCell<>() { private final Label title=new Label(); private final Label meta=new Label(); private final Label badge=new Label(); private final Region spacer=new Region(); private final HBox row=new HBox(12,new VBox(3,title,meta),spacer,badge); { HBox.setHgrow(spacer,Priority.ALWAYS); title.getStyleClass().add("profile-name"); meta.getStyleClass().add("helper-text"); badge.getStyleClass().add("status"); } protected void updateItem(AssignmentClearance item,boolean empty){super.updateItem(item,empty);if(empty||item==null){setGraphic(null);setText(null);return;}title.setText(item.profile()==null?"Unknown profile":item.profile().name());meta.setText(item.assignment().project()+"  ·  "+item.assignment().status().label());badge.setText(item.clearance().label());badge.getStyleClass().removeAll("status-current","status-expiring","status-expired");badge.getStyleClass().add(switch(item.clearance()){case CLEARED->"status-current";case AT_RISK->"status-expiring";case BLOCKED->"status-expired";});setGraphic(row);setText(null);}});
        Button add=new Button("+ Add assignment");add.getStyleClass().add("primary");add.setOnAction(e->edit(null)); Button remove=new Button("Unassign selected");remove.getStyleClass().add("danger");remove.setDisable(true);list.getSelectionModel().selectedItemProperty().addListener((o,a,v)->remove.setDisable(v==null));
        remove.setOnAction(e->{AssignmentClearance selected=list.getSelectionModel().getSelectedItem();if(selected==null)return;Alert confirm=new Alert(Alert.AlertType.CONFIRMATION,"This removes the person from the project assignment. Documents are not deleted.",ButtonType.CANCEL,ButtonType.OK);confirm.setHeaderText("Unassign from project");confirm.showAndWait().filter(b->b==ButtonType.OK).ifPresent(b->{try{assignments.delete(selected.assignment().id());refresh();}catch(RuntimeException ex){notifications.error("Assignment could not be removed.");}});});
        list.getSelectionModel().selectedItemProperty().addListener((o,a,v)->showDetails(v));list.setOnMouseClicked(e->{if(e.getClickCount()==2&&list.getSelectionModel().getSelectedItem()!=null)edit(list.getSelectionModel().getSelectedItem().assignment());});
        Label hint=new Label("Double-click an assignment to edit its project, person, or review status.");hint.getStyleClass().add("helper-text");selectedDetails.setWrapText(true);selectedDetails.getStyleClass().add("helper-text");
        VBox detailCard=new VBox(10,new Label("Readiness details"),selectedDetails);detailCard.getStyleClass().add("card");FlowPane actions=new FlowPane(10,8,add,remove);actions.getStyleClass().add("toolbar");VBox listCard=new VBox(14,list,actions,hint);SplitPane split=new SplitPane(listCard,detailCard);split.setDividerPositions(.68);split.getStyleClass().add("document-split");split.widthProperty().addListener((o,a,w)->split.setOrientation(w.doubleValue()<760?Orientation.VERTICAL:Orientation.HORIZONTAL));split.setOrientation(Orientation.HORIZONTAL);VBox card=new VBox(14,split);card.getStyleClass().addAll("card","assignments-card");setCenter(card);refresh();
    }
    public void refresh(){list.getItems().setAll(clearance.list());}
    private void showDetails(AssignmentClearance value){if(value==null){selectedDetails.setText("Select an assignment to see its readiness details.");return;}String issues=value.issues().isEmpty()?"No blocking issues. This assignment is ready.":value.issues().stream().map(issue->"• "+issue).collect(java.util.stream.Collectors.joining("\n"));selectedDetails.setText("Project: "+value.assignment().project()+"\nProfile: "+(value.profile()==null?"Unknown profile":value.profile().name())+"\nStatus: "+value.clearance().label()+"\n\n"+issues);}
    private void edit(ProjectAssignment existing){if(profiles.list().isEmpty()){notifications.error("Create a profile before assigning someone to a project.");return;}Dialog<ProjectAssignment> dialog=new Dialog<>();dialog.setTitle(existing==null?"Add assignment":"Edit assignment");dialog.getDialogPane().getButtonTypes().addAll(ButtonType.CANCEL,ButtonType.OK);ComboBox<String> project=new ComboBox<>(FXCollections.observableArrayList(projects));project.setEditable(true);project.setValue(existing==null?null:existing.project());Map<String,Profile> byName=new LinkedHashMap<>();profiles.list().forEach(p->byName.put(p.name(),p));ComboBox<String> profile=new ComboBox<>(FXCollections.observableArrayList(byName.keySet()));if(existing!=null)byName.values().stream().filter(p->p.id()==existing.profileId()).findFirst().ifPresent(p->profile.setValue(p.name()));ComboBox<AssignmentStatus> status=new ComboBox<>(FXCollections.observableArrayList(AssignmentStatus.values()));status.setValue(existing==null?AssignmentStatus.PENDING:existing.status());TextField notes=new TextField(existing==null?"":existing.notes());GridPane grid=new GridPane();grid.setHgap(14);grid.setVgap(12);grid.setPadding(new Insets(12));grid.addRow(0,new Label("Project"),project);grid.addRow(1,new Label("Profile"),profile);grid.addRow(2,new Label("Review status"),status);grid.addRow(3,new Label("Notes"),notes);dialog.getDialogPane().setContent(grid);dialog.setResultConverter(button->{Profile selected=byName.get(profile.getValue());return button==ButtonType.OK&&selected!=null?new ProjectAssignment(existing==null?0:existing.id(),project.getEditor().getText(),selected.id(),status.getValue(),notes.getText()):null;});dialog.showAndWait().ifPresent(value->{try{assignments.save(value);refresh();}catch(IllegalArgumentException ex){notifications.error(ex.getMessage());}});}
}
