package com.permitping.ui;

import com.permitping.application.*;
import com.permitping.domain.*;
import com.permitping.infrastructure.FileStorage;
import javafx.collections.FXCollections;
import javafx.geometry.Insets;
import javafx.scene.Node;
import javafx.scene.control.*;
import javafx.scene.layout.*;
import javafx.stage.FileChooser;
import java.io.File;
import java.io.IOException;
import java.nio.file.Path;
import java.time.LocalDate;
import java.util.Objects;
import java.util.function.Consumer;

public final class DocumentForm {
    private final DocumentService service; private final ProfileService profiles; private final FileStorage files; private final DocumentVersionService versions; private final NotificationService notifications;
    public DocumentForm(DocumentService service, ProfileService profiles, FileStorage files, DocumentVersionService versions, NotificationService notifications){this.service=service;this.profiles=profiles;this.files=files;this.versions=versions;this.notifications=notifications;}
    public void show(Document existing,Consumer<Document> onSaved){showInternal(existing,false,onSaved);}
    public void showRenewal(Document existing,Consumer<Document> onSaved){showInternal(existing,true,onSaved);}
    private void showInternal(Document existing,boolean renewal,Consumer<Document> onSaved){
        Dialog<Document> dialog=new Dialog<>(); dialog.setTitle(renewal?"Renew compliance document":existing==null?"Add compliance document":"Edit compliance document"); dialog.getDialogPane().getStyleClass().add("workspace-dialog"); ButtonType back=new ButtonType("Back",ButtonBar.ButtonData.OTHER),next=new ButtonType("Next",ButtonBar.ButtonData.OTHER),save=new ButtonType(renewal?"Save renewal":"Save document",ButtonBar.ButtonData.OK_DONE); dialog.getDialogPane().getButtonTypes().addAll(back,next,save,ButtonType.CANCEL);
        TextField name=new TextField(value(existing==null?null:existing.name())); ComboBox<String> holder=new ComboBox<>(); holder.setEditable(true); holder.getItems().setAll(profiles==null?java.util.List.of():profiles.list().stream().map(Profile::name).toList()); holder.getEditor().setText(value(existing==null?null:existing.holder())); TextField project=new TextField(value(existing==null?null:existing.project())),path=new TextField(value(existing==null?null:existing.filePath())),notes=new TextField(value(existing==null?null:existing.notes())); ComboBox<String> type=new ComboBox<>(FXCollections.observableArrayList("License","Insurance certificate","OSHA card","Permit","Subcontractor document","Other")); type.setValue(existing==null?"License":existing.type()); DatePicker expires=new DatePicker(renewal||existing==null?LocalDate.now().plusDays(365):existing.expiresOn()); Label error=new Label(); error.getStyleClass().add("form-error");
        GridPane first=page("1  Document and holder"); add(first,0,"Document name",name); add(first,1,"Document type",type); add(first,2,"Holder / company",holder);
        GridPane second=page("2  Expiration and project"); add(second,0,"Expiration date",expires); HBox shortcuts=new HBox(6); for(String shortcut:new String[]{"Today","+30 days","+90 days","+1 year"}){Button b=new Button(shortcut);b.getStyleClass().add("secondary");b.setOnAction(e->expires.setValue(switch(shortcut){case "Today"->LocalDate.now();case "+30 days"->LocalDate.now().plusDays(30);case "+90 days"->LocalDate.now().plusDays(90);default->LocalDate.now().plusYears(1);}));shortcuts.getChildren().add(b);} add(second,1,"Quick dates",shortcuts); add(second,2,"Project (optional)",project);
        GridPane third=page("3  File and reminder settings"); Button browse=new Button("Choose file"); browse.getStyleClass().add("secondary"); browse.setOnAction(e->{FileChooser fc=new FileChooser();File file=fc.showOpenDialog(dialog.getOwner());if(file!=null)path.setText(file.getAbsolutePath());}); HBox file=new HBox(8,path,browse); HBox.setHgrow(path,Priority.ALWAYS); add(third,0,"File (optional)",file); add(third,1,"Notes (optional)",notes); Label reminder=new Label("Reminder settings are managed from the Reminders page."); reminder.getStyleClass().add("muted"); add(third,2,"Reminders",reminder);
        StackPane pages=new StackPane(first,second,third); pages.getStyleClass().add("form-pages"); third.setVisible(false); second.setVisible(false); VBox content=new VBox(10,pages,error); content.getStyleClass().add("form-content"); dialog.getDialogPane().setContent(content); dialog.getDialogPane().setPadding(new Insets(4));
        Button backButton=(Button)dialog.getDialogPane().lookupButton(back),nextButton=(Button)dialog.getDialogPane().lookupButton(next),saveButton=(Button)dialog.getDialogPane().lookupButton(save); backButton.setDisable(true); saveButton.setVisible(false);
        nextButton.addEventFilter(javafx.event.ActionEvent.ACTION,e->{e.consume();if(first.isVisible()&&!validateFirst(name,type,holder,error)){return;}if(second.isVisible()&&!validateSecond(expires,error)){return;}if(first.isVisible()){first.setVisible(false);second.setVisible(true);backButton.setDisable(false);}else if(second.isVisible()){second.setVisible(false);third.setVisible(true);nextButton.setVisible(false);saveButton.setVisible(true);}});
        backButton.addEventHandler(javafx.event.ActionEvent.ACTION,e->{e.consume();if(third.isVisible()){third.setVisible(false);second.setVisible(true);nextButton.setVisible(true);saveButton.setVisible(false);}else if(second.isVisible()){second.setVisible(false);first.setVisible(true);backButton.setDisable(true);}});
        saveButton.addEventFilter(javafx.event.ActionEvent.ACTION,e->{e.consume();Document candidate=build(existing,renewal,name,type,holder,project,expires,path,notes);if(!validateAll(candidate,path,error))return;try{Document savedDocument=persist(candidate,existing);dialog.setResult(savedDocument);dialog.close();onSaved.accept(savedDocument);}catch(IllegalArgumentException|IOException ex){error.setText(ex.getMessage()==null?"The document could not be saved.":ex.getMessage());error.getStyleClass().remove("form-warning");error.getStyleClass().add("form-error");}}); dialog.showAndWait();
    }
    private Document persist(Document candidate,Document existing) throws IOException { Document submitted=candidate;if(profiles!=null){String holderName=submitted.holder();profiles.ensure(holderName);Profile p=profiles.list().stream().filter(profile->profile.name().equalsIgnoreCase(holderName)).findFirst().orElse(null);submitted=new Document(submitted.id(),submitted.name(),submitted.type(),submitted.holder(),submitted.project(),submitted.expiresOn(),submitted.filePath(),submitted.notes(),p==null?0:p.id());}String selectedPath=submitted.filePath();Path importedPath=null;if(selectedPath!=null&&!selectedPath.isBlank()&&!files.isManaged(selectedPath)){Path source=Path.of(selectedPath);if(files.isDuplicate(source,existing==null?null:existing.filePath()))notifications.info("A duplicate file already exists in managed storage.");importedPath=files.importFile(source);selectedPath=importedPath.toString();submitted=new Document(submitted.id(),submitted.name(),submitted.type(),submitted.holder(),submitted.project(),submitted.expiresOn(),selectedPath,submitted.notes(),submitted.holderProfileId());}Document savedDocument;try{savedDocument=service.save(submitted);}catch(RuntimeException ex){if(importedPath!=null)try{files.deleteManagedFile(importedPath);}catch(IOException cleanupFailure){ex.addSuppressed(cleanupFailure);}throw ex;}if(versions!=null&&(existing==null||!Objects.equals(existing.filePath(),savedDocument.filePath())))versions.record(savedDocument.id(),savedDocument.filePath());return savedDocument;}
    private Document build(Document existing,boolean renewal,TextField name,ComboBox<String> type,ComboBox<String> holder,TextField project,DatePicker expires,TextField path,TextField notes){return new Document(existing==null?0:existing.id(),name.getText().trim(),type.getValue(),holder.getEditor().getText().trim(),project.getText().trim(),expires.getValue(),path.getText().trim(),notes.getText().trim(),existing==null?0:existing.holderProfileId());}
    private boolean validateFirst(TextField name,ComboBox<String> type,ComboBox<String> holder,Label error){boolean valid=true;valid&=required(name);valid&=required(type);valid&=required(holder.getEditor());error.setText(valid?"":"Complete the document name, type, and holder before continuing.");return valid;}
    private boolean validateSecond(DatePicker expires,Label error){boolean valid=expires.getValue()!=null;mark(expires,!valid);error.setText(valid?"":"Choose an expiration date before continuing.");return valid;}
    private boolean validateAll(Document candidate,TextField path,Label error){error.getStyleClass().remove("form-warning");if(!validateFirstControl(candidate,error)||!validateSecondValue(candidate,error))return false;if(candidate.expiresOn().isBefore(LocalDate.now())){error.setText("Warning: this document is already expired.");error.getStyleClass().add("form-warning");}if(!validateFile(candidate.filePath(),path,error))return false;if(service.isDuplicate(candidate)){error.setText("A document with this name, holder, and project already exists.");return false;}return true;}
    private boolean validateFile(String value,TextField field,Label error){if(value==null||value.isBlank()){mark(field,false);return true;}try{Path file=Path.of(value);if(!java.nio.file.Files.isRegularFile(file)){mark(field,true);error.setText("The selected file does not exist.");return false;}String name=file.getFileName().toString().toLowerCase();if(!(name.endsWith(".pdf")||name.endsWith(".png")||name.endsWith(".jpg")||name.endsWith(".jpeg")||name.endsWith(".doc")||name.endsWith(".docx"))){mark(field,true);error.setText("Use a supported file type: PDF, image, or Word document.");return false;}mark(field,false);return true;}catch(Exception ex){mark(field,true);error.setText("Enter a valid file path.");return false;}}
    private boolean validateFirstControl(Document d,Label error){boolean valid=d.name()!=null&&!d.name().isBlank()&&d.type()!=null&&!d.type().isBlank()&&d.holder()!=null&&!d.holder().isBlank();error.setText(valid?"":"Complete the document name, type, and holder before saving.");return valid;}
    private boolean validateSecondValue(Document d,Label error){boolean valid=d.expiresOn()!=null;error.setText(valid?"":"Choose an expiration date before saving.");return valid;}
    private boolean required(Control c){boolean valid=c instanceof TextInputControl t?!t.getText().isBlank():((ComboBox<?>)c).getValue()!=null;mark(c,!valid);return valid;}
    private void mark(Control c,boolean error){if(error&&!c.getStyleClass().contains("field-error"))c.getStyleClass().add("field-error");if(!error)c.getStyleClass().remove("field-error");}
    private GridPane page(String title){GridPane g=new GridPane();g.getStyleClass().add("form-page");g.setHgap(16);g.setVgap(16);g.setPadding(new Insets(18));Label heading=new Label(title);heading.getStyleClass().add("form-step");g.add(heading,0,0,2,1);return g;}
    private void add(GridPane g,int row,String label,Node node){Label caption=new Label(label);caption.getStyleClass().add("form-label");g.add(caption,0,row+1);g.add(node,1,row+1);GridPane.setHgrow(node,Priority.ALWAYS);}
    private String value(String s){return s==null?"":s;}
}
