package com.permitping.domain;

public enum Permission {
    VIEW_DOCUMENTS, MANAGE_DOCUMENTS, VIEW_PROFILES, MANAGE_PROFILES,
    MANAGE_ASSIGNMENTS, MANAGE_REMINDERS, VIEW_REPORTS, MANAGE_SETTINGS,
    MANAGE_USERS, VIEW_AUDIT
}
